dist: focal
language: go
go:
  - 1.13

before_install:
  - sudo apt-get update
  - sudo apt-get install git jq wget graphviz
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i *.deb
  - sudo gem install asciidoctor asciidoctor-diagram
  - go version

script:
  - git clone https://git.sr.ht/~sircmpwn/openring && cd openring && go build && cd ../
  - chmod +x ./bin/openring-create && ./bin/openring-create
  - hugo

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.76.0

deploy:
  local_dir: "./public/"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: gh-pages
  on:
    branch: master

