dist: focal
language: nix

script:
  - nix-shell shell.nix
  - git clone https://git.sr.ht/~sircmpwn/openring && cd openring && go build && cd ../
  - chmod +x ./bin/openring-create && ./bin/openring-create
  - hugo

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.76.0

deploy:
  local_dir: "./public/"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: gh-pages
  on:
    branch: master

